In [3]:
import numpy as np

In [4]:
t2 = np.array([[1,2,3],[4,5,6]])
print(t2)
print(t2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [6]:
t3 = np.arange(24).reshape(2,3,4)
print(t3)
print(t3.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [7]:
t3.reshape(4,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [8]:
#变成一维
t4 = t3.reshape(24,)
print(t4)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
t5 = t4.reshape(1,24)
print(t5)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


In [10]:
t6 = t5.reshape(24,1)
print(t6)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]


In [12]:
t7 = t6.flatten()
print(t7)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [13]:
print(t3)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [14]:
t8 = np.arange(24).reshape(4,6)
print(t8)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [16]:
t9 = np.arange(24,48)
print(t9)

[24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]


In [32]:
t10 = np.arange(24).reshape(3,2,4)
print(t10)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [39]:
t11 = np.arange(8).reshape(2,4)
print(t11)

[[0 1 2 3]
 [4 5 6 7]]


In [40]:
t12 = t10 - t11
print(t12)

[[[ 0  0  0  0]
  [ 0  0  0  0]]

 [[ 8  8  8  8]
  [ 8  8  8  8]]

 [[16 16 16 16]
  [16 16 16 16]]]
